/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
import java.util.function.Supplier

plugins {
    `java-gradle-plugin`
}

val gradleLibraryVersion by extra(provider { "7.5-20220504230242+0000" })

@DisableCachingByDefault(because = "Writing to the file directly is faster then loading it from the cache")
open class WriteTextInDir : DefaultTask() {

    @Internal
    var data: Supplier<String>? = null

    @OutputDirectory
    var dir: File? = null

    @Input
    var fileName: String? = null

    private var _data: String? = null

    init {
        dir = project.file("${project.buildDir}/$name")
        fileName = "$name.txt"
    }

    @Input
    fun getText(): String {
        if (_data == null) {
            _data = data!!.get()
        }
        return _data!!
    }

    @TaskAction
    fun write() {
        dir!!.deleteRecursively()
        dir!!.mkdirs()
        File(dir, fileName).writeText(getText(), Charsets.UTF_8)
    }
}

val gradleLibraryVersionFile by tasks.registering(WriteTextInDir::class) {
    dir = file("$buildDir/$name")
    fileName = "com.sorinflorea.gradleLibraryVersion.txt"
    val gradleLibraryVersion: Provider<String> by rootProject.extra
    data = Supplier { gradleLibraryVersion.get() }
}

dependencies {
    implementation(gradleLibraryVersionFile.map { it.outputs.files })
}
